config/routes.rb
SportsReservations::Application.routes.draw do
  resources :prices

  resources :reservations

get "/tennis_facilities/search"
  resources :tennis_facilities

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/tennis_facility.rb
class TennisFacility < ActiveRecord::Base
geocoded_by :address
after_validation :geocode, :if => :address_changed?

def self.search(search)
    if search['zipcode'].present?
      	find(:all, :conditions => ['zipcode= ?', search['zipcode']])
    elsif search['id'].present?
      	find(:all, :conditions => ['id= ?', search['id']])
    elsif search['name'].present?
      	find(:all, :conditions => ['name= ?', search['name']])
    elsif search['city'].present?
      	find(:all, :conditions => ['city= ?', search['city']])
    else
      	find(:all)
    end
 end

end

app/controllers/tennis_facilities_controller.rb
class TennisFacilitiesController < ApplicationController
  before_action :set_tennis_facility, only: [:show, :edit, :update, :destroy]

  def courts_by_id(facilityId)
    :search['id'] = facilityId
    @tennis_facility = TennisFacility.search(params[:search])
    @tennis_facility.courts
  end

  # GET /tennis_facilities
  # GET /tennis_facilities.json
  def index
    if params[:search].present?
      @tennis_facilities = TennisFacility.search(params[:search])
    else
      @tennis_facilities = TennisFacility.find(:all)
    end
  end

  # def search
  #   @tennis_facilities = TennisFacility.search(params[:search])
  # end

  # GET /tennis_facilities/1
  # GET /tennis_facilities/1.json
  def show
  end

  # GET /tennis_facilities/new
  def new
    @tennis_facility = TennisFacility.new
  end

  # GET /tennis_facilities/1/edit
  def edit
  end

  # POST /tennis_facilities
  # POST /tennis_facilities.json
  def create
    @tennis_facility = TennisFacility.new(tennis_facility_params)

    respond_to do |format|
      if @tennis_facility.save
        format.html { redirect_to @tennis_facility, notice: 'Tennis facility was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tennis_facility }
      else
        format.html { render action: 'new' }
        format.json { render json: @tennis_facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tennis_facilities/1
  # PATCH/PUT /tennis_facilities/1.json
  def update
    respond_to do |format|
      if @tennis_facility.update(tennis_facility_params)
        format.html { redirect_to @tennis_facility, notice: 'Tennis facility was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tennis_facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tennis_facilities/1
  # DELETE /tennis_facilities/1.json
  def destroy
    @tennis_facility.destroy
    respond_to do |format|
      format.html { redirect_to tennis_facilities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

     def set_tennis_facility
      @tennis_facility = TennisFacility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tennis_facility_params
      params.require(:tennis_facility).permit(:name, :address, :zipcode, :city, :courts, :lights, :courtstypes, :comments, :phone)
    end
end

app/helpers/tennis_facilities_helper.rb
module TennisFacilitiesHelper
end

app/views/tennis_facilities/_form.html.erb
<%= simple_form_for(@tennis_facility) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :zipcode %>
    <%= f.input :city %>
    <%= f.input :courts %>
    <%= f.input :lights %>
    <%= f.input :courtstypes %>
    <%= f.input :comments %>
    <%= f.input :phone %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tennis_facilities/edit.html.erb
<h1>Editing tennis_facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @tennis_facility %> |
<%= link_to 'Back', tennis_facilities_path %>

app/views/tennis_facilities/index.html.erb
<%= simple_form_for :search,  url: tennis_facilities_path , :method => :get do |f| %>
    <%= f.input :zipcode, :autofocus => true %>
    <%= f.submit "Search" %>
<% end %>
<h1>Listing Tennis Facilities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Zipcode</th>
      <th>City</th>
      <th>Courts</th>
      <th>Lights</th>
      <th>Court Type</th>
      <th>Comments</th>
      <th>Phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tennis_facilities.each do |tennis_facility| %>
      <tr>
        <td><%= tennis_facility.name %></td>
        <td><%= tennis_facility.address %></td>
        <td><%= tennis_facility.zipcode %></td>
        <td><%= tennis_facility.city %></td>
        <td><%= tennis_facility.courts %></td>
        <td><%= tennis_facility.lights %></td>
        <td><%= tennis_facility.courtstypes %></td>
        <td><%= tennis_facility.comments %></td>
        <td><%= tennis_facility.phone %></td>
        
        <td><%= link_to 'Reserve', reservations_path(:facilityId => tennis_facility.id, :courts => tennis_facility.courts) %></td>
        
        <td><%= link_to 'Show Map', tennis_facility %></td>
        <td><%= link_to 'Pricing', prices_path(:facilityId => tennis_facility.id) %></td>
        <td><%= link_to 'Edit', edit_tennis_facility_path(tennis_facility) %></td>
        <!--<td><%= link_to 'Destroy', tennis_facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tennis Facility', new_tennis_facility_path %><br/>

app/views/tennis_facilities/new.html.erb
<h1>New Tennis Facility</h1>

<%= render 'form' %>

<%= link_to 'Back', tennis_facilities_path %>

app/views/tennis_facilities/search.html.erb
<h1>Search Tennis Facilities</h1>
<%= simple_form_for :search,  url: tennis_facilities_path , :method => :get do |f| %>
    <%= f.input :zipcode, :autofocus => true %>
    <%= f.submit "Search" %>
    <!--<%=f.input :zipcode, :autofocus => true %>
    <<%= f.input :zipcode, :autofocus => true %>
    <%= f.input :city, :autofocus => true %>
    <%= f.input :name, :autofocus => true %>
    <%= f.input :id, :autofocus => true %>-->
<% end %>


<%= link_to 'Back', tennis_facilities_path %>

app/views/tennis_facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tennis_facility.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @tennis_facility.address %>
</p>

<!--<p>
  <strong>Zipcode:</strong>
  <%= @tennis_facility.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @tennis_facility.city %>
</p>

<p>
  <strong>Courts:</strong>
  <%= @tennis_facility.courts %>
</p>

<p>
  <strong>Lighted:</strong>
  <%= @tennis_facility.lights %>
</p>

<p>
  <strong>Courtstypes:</strong>
  <%= @tennis_facility.courtstypes %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @tennis_facility.comments %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @tennis_facility.phone %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @tennis_facility.latitude %>
</p>-->

<td>
<%= image_tag src=
  "http://maps.googleapis.com/maps/api/staticmap?center=#{@tennis_facility.latitude},#{@tennis_facility.longitude}&zoom=12&size=400x400&maptype=roadmap&markers=color:red%7Ccolor:red%7Clabel:C%7C
  #{@tennis_facility.latitude},#{@tennis_facility.longitude}
  &sensor=false" %>
</td>





<%= link_to 'Edit', edit_tennis_facility_path(@tennis_facility) %> |
<%= link_to 'Back', tennis_facilities_path %>