config/routes.rb
SportsReservations::Application.routes.draw do
  resources :prices

  resources :reservations

get "/tennis_facilities/search"
  resources :tennis_facilities

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

def self.search(search)
    if search['itemId'].present? && 
    	search['starttime'].present? &&
    	search['endtime'].present? &&
      search['facilityId'].present?
    	res = nil
    	#if(Person.exists?(['name LIKE ?', "%#{query}%"]))
    	if(Reservation.exists?(['itemId=? AND starttime=? 
      											AND endtime=? AND facilityId=?', 
      						search['itemId'],
      						search['starttime'],
      						search['endtime'],
                  search['facilityId']])) then
      		res = Reservation.find(:all,:conditions => ['itemId=? AND starttime=? 
      											AND endtime=? AND facilityId=?', 
      						search['itemId'],
      						search['starttime'],
      						search['endtime'],
                  search['facilityId']])
      	end
		
	end
end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  

  # GET /reservations
  # GET /reservations.json
  def index
    if params[:search].present?
      @reservations = Reservation.search(params[:search])
    else
      #@reservations = Reservation.find(:all)
      @reservations = Reservation.all
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @reservation.facilityId = params[:facilityId]
    @reservation.itemId = params[:itemId]
    @reservation.starttime = params[:starttime]
    @reservation.endtime = params[:endtime]
    @reservation.players = params[:players]
    @prices = Price.all.map {|r| [r.reservationType, r.id]}
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reservation }
      else
        format.html { render action: 'new' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    @reservation.facilityId = params[:facilityId]
    @reservation.itemId = params[:itemId]
    @reservation.starttime = params[:starttime]
    @reservation.endtime = params[:endtime]
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end


  #private
  public
    
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:itemId, :priceId, :userId, :statusId, :players, :user, :comments, :starttime, :endtime, :facilityId, :status)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= simple_form_for @reservation  do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :itemId %>
    <%= f.input :players, collection: 1..10 %>
    <%= f.input :priceId, collection: @prices %>
    <!--<%= f.input :user %>-->
    <%= f.input :comments %>
    <%= f.input :starttime %>
    <%= f.input :endtime %>
    <%= f.input :facilityId %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <% if !@reservation.id.nil? %>
    <%= @reservation.inspect %>
    <%= link_to 'Cancel', @reservation, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing Reservations</h1>
<table>
    <tr>
      <th> Time: </th>
      <th> 6-7 </th>
      <th> 7-8 </th>
      <th> 8-9 </th>
      <th> 9-10     </th>
      <th> 10-11    </th>
      <th> 11-12    </th>
      <th> 12-13    </th>
      <th> 13-14    </th>
      <th> 14-15    </th>
      <th> 15-16    </th>
      <th> 16-17    </th>
      <th> 17-18    </th>
      <th> 18-19    </th>
      <th> 19-20    </th>
      <th> 20-21    </th>
      <th> 21-22    </th>
    </tr>
      <% for i in 1..params[:courts].to_i%>
        <tr>
            <td>Court: <%= i %></td>
            <%time_ary = [6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]%>
            <%time_ary.each do |j|%>
                <% search = { "itemId" => i, "starttime" => j, "endtime" => j+1 , "facilityId" => params[:facilityId]} %>
                <% res = Reservation.search(search) %>
                <% if (res != nil)  %>
                  <td><%= link_to 'Edit/Cancel', edit_reservation_path(res),
                  {:style=>'color:GREEN;', :class => "css_class"}  %>
                  </td>
                <% else %>
                  <td><%= link_to 'Reserve', 
                        new_reservation_path(:itemId => i, :facilityId =>params[:facilityId],
                        :starttime=>j, :endtime=>j+1, :players=>2),
                        {:style=>'color:RED;', :class => "css_class"}  %></td>
                <%end%>
            <%end%>  
        </tr>

      <%end%>
      </table>
  
   

  

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Reservation:</strong>
  <%= @reservation.itemId %>
</p>

<p>
<string>Players:</strong>
  <%= @reservation.players %>
</p>

<p>
<string>User:</strong>
  <%= @reservation.user%>
</p>

<p>
<string>Comments:</strong>
  <%=  @reservation.comments%>
</p>

<p>
<string>Start Time:</strong>
  <%=  @reservation.starttime%>
</p>

<p>
<string>End Time:</strong>
  <%=  @reservation.endtime%>
</p>

<p>
<string>Facility Id:</strong>
  <%= @reservation.facilityId%>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>