config/routes.rb
SportsReservations::Application.routes.draw do
  resources :prices

  resources :reservations

get "/tennis_facilities/search"
  resources :tennis_facilities

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/price.rb
class Price < ActiveRecord::Base

# def self.search(search)
#     if search['facilityId'].present? 
#     	res = nil
#     	if(Price.exists?(['facilityId=?',
#                   search['facilityId']])) then
#       		res = Price.find(:all,:conditions => ['facilityId=?', 
#                   search['facilityId']])
#       	end
		
# 	end
# end

def self.search(facilityId)
    if facilityId.present?
    	res = nil
    	if(Price.exists?(['facilityId=?',
                facilityId])) then
      		res = Price.find(:all,:conditions => ['facilityId=?', 
                  facilityId])
      	end
		
	end
end

def self.search1(reservationType)
    if reservationType.present?
    	res = nil
    	if(Price.exists?(['reservationType=?',
                reservationType])) then
      		res = Price.find(:all,:conditions => ['reservationType=?', 
                  reservationType])
      	end
		
	end
end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    #@prices = Price.all
    # if params[:search].present?
    #   @prices = Price.search(params[:search])
    #:search = :facilityId
    #params[:search].to_yaml
    #debug params[:search]
    # if params[:facilityId].present?
    #   @prices = Price.search(params[:facilityId])
    if params[:facilityId].present?
      @prices = Price.search(params[:facilityId])
    elsif params[:reservationType].present?
      @prices = Price.search1(params[:reservationType])
    else
      @prices = Price.all
    end
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
    @price.facilityId = params[:facilityId]
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)
    @price.facilityId = price_params[:facilityId]

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render action: 'show', status: :created, location: @price }
      else
        format.html { render action: 'new' }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    @price.facilityId = params[:facilityId]
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:reservationType, :reservationPrice, :pricingDescription, :facilityId, :players)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= simple_form_for(@price) do |f| %>
  <%= f.error_notification %>
<!--<%= @price.facilityId.inspect  %>-->

  <div class="form-inputs">
    <%= f.input :reservationType %>
    <%= f.input :reservationPrice %>
    <%= f.input :pricingDescription %>
    <%= f.input :facilityId %>
    <%= f.input :players %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<h1>Listing prices</h1>
<!--<%=params[:facilityId].inspect%>-->
<% if !@prices.nil? %>
      <table>
        <thead>
          <tr>
            <th>Reservation Type</th>
            <th>Reservation Price</th>
            <th>Pricing Description</th>
            <th>Facility Id</th>
            <th>Players</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @prices.each do |price| %>
            <tr>
              <td><%= price.reservationType %></td>
              <td><%= price.reservationPrice %></td>
              <td><%= price.pricingDescription %></td>
              <td><%= price.facilityId %></td>
              <td><%= price.players %></td>
              <td><%= link_to 'Show', price %></td>
              <td><%= link_to 'Edit', edit_price_path(price) %></td>
              <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
<% end %>
<br>

<%= link_to 'New Price', new_price_path(:facilityId =>params[:facilityId]) %>

app/views/prices/new.html.erb
<h1>New price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reservation Type:</strong>
  <%= @price.reservationType %>
</p>

<p>
  <strong>Reservation Price:</strong>
  <%= @price.reservationPrice %>
</p>

<p>
  <strong>Pricing Description:</strong>
  <%= @price.pricingDescription %>
</p>

<p>
  <strong>Facility Id:</strong>
  <%= @price.facilityId %>
</p>

<p>
  <strong>Players:</strong>
  <%= @price.players %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>