config/routes.rb
SportsReservations::Application.routes.draw do
  resources :prices

  resources :reservations

get "/tennis_facilities/search"
  resources :tennis_facilities

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation 4 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to 'SPORTS FACILITIES AND RESERVATIONS', root_path %></li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li> 
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'LOGOUT', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'LOGIN', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'SIGN UP', new_user_registration_path %></li>
<% end %>


<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <li><%= link_to 'Admin', users_path %></li>
  <% end %>
<% end %>


  <li><%= link_to 'LISTINGS', tennis_facilities_path %></li>

  <!--<li><%= link_to 'SEARCH', tennis_facilities_search_path %></li>-->

  <li><%= link_to 'ALERTS', "" %></li>

  <li><%= link_to 'FORUM', "" %></li>
  





 
  

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sports Reservations" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sports Reservations" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation 4 %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>